### ISSUE TITLE
Multiple notification

### ISSUE THREAD

**Issue by balthazar** [42Zavattas/42Stack#11]

**Comment by balthazar** [comment]
Fixed in https://github.com/42Zavattas/42Stack/commit/743c4f38223b7c4cc8cc90a25405467e13b327ee

**Comment by balthazar** [comment]
The routeChangeStart is triggered when a post request is done (upvote / downvote / accept). It causes issues because the listeners are deleted but the user is still on a page, without sockets.

**Comment by meriadec** [comment]
interesting. lets fix it tomorrow.

**Comment by balthazar** [comment]
Fixed in https://github.com/42Zavattas/42Stack/commit/c83d5126608541d025c1350fab71eed7feb078d4, I've called the removeAllListeners at the beginning of the main and questions controllers  to prevent reset on each request.

**Comment by balthazar** [comment]
Really fixed in https://github.com/42Zavattas/42Stack/commit/bb40fa13c96a4f3323f3bef7bd17107386e0f115, created a service to reset the Sockets correctly and re-bind the clearCache listener automatically.
